$axure.loadCurrentPage({
  "url":"游戏画面_1.html",
  "generationDate":new Date(1461642319337.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7d14f5f6387a427d92a5e9bfbc496cf5",
    "type":"Axure:Page",
    "name":"游戏画面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"451d1646a98e40c98bd0b8a2d7905760",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":20},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"673a81cffa3d473098bff8ceadb621d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":20},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u0.png"}},
{
          "id":"07e1d5527d924a37a4fe147fabbf9264",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":220},
            "size":{
              "width":320,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec137798726f48a78af7d1e6196ab145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":152,
                  "y":220},
                "size":{
                  "width":320,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u2.png"}},
{
          "id":"f9c1003f2358478eb4fa2414b71e85f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":255,
              "y":600},
            "size":{
              "width":105,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05e2fcd50bed4b76ab306e4e43769fea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":255,
                  "y":600},
                "size":{
                  "width":105,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u4.png"}},
{
          "id":"6038c64abdeb42c58eb655304ca7820b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":163,
              "y":613},
            "size":{
              "width":93,
              "height":77},
            "rotation":"338",
            "textRotation":"338"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"944fbe3aace149fd883ee6fad6f18f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":163,
                  "y":613},
                "size":{
                  "width":93,
                  "height":77},
                "rotation":"338",
                "textRotation":"338"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u6.png"}},
{
          "id":"bbe0ef78c9c24740af24584316cb6829",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":609},
            "size":{
              "width":93,
              "height":77},
            "rotation":"12",
            "textRotation":"12"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9692f1d3380144829301ee5774e936c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":609},
                "size":{
                  "width":93,
                  "height":77},
                "rotation":"12",
                "textRotation":"12"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u8.png"}},
{
          "id":"8572705a1cb244afbdbd8728de1e7adc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":143},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"72349d41325a409b9ca365a96dd71ef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":158,
              "y":140},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b40ae6922f5e4fae9fadcc338f47e6f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":158,
                  "y":140},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f449b3d29f54e93bbe20a27b0a34fb1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":164},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"5a5dde7c53d5419193fefa944165f34c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":158,
              "y":161},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"478159907dc64297b25dd30549b463c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":158,
                  "y":161},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37f16c4e512940ce9f9a684cb93169fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":185},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"4a21d37340cf4c329a396a50f7bd1579",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":158,
              "y":182},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29dd4441eb3743908f5d99e69b2a9097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":158,
                  "y":182},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c87c564099c42ceb061547874755bdd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":205},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"9fb5d8481f204939907c5b49b13311de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":172,
              "y":202},
            "size":{
              "width":15,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b9d00d754149ac94937213cd1bdd51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":172,
                  "y":202},
                "size":{
                  "width":15,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c71e41cb7fb40bf887ba200b29b37f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":143},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"ec8408f447514644bc1f5016c6a5edd3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"23ca070254b441a8b76cc288a6379576",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":185},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"5b75b3ace37f410495cf829ea081ba5e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":205},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"1e4bd85d50744d799cdf00f53ef05626",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":143},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"f9ce1c13c7534062bd57e31bed644433",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":164},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"163beab19e8e4810a0f88d184841c92e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":185},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"55926679b10e4a6bb9f058a3dd16e5a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":305,
              "y":205},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"dc1269b2da894c25a7fb46585e3381bc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":143},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"766f45261df94d5096ce5d29f2bc007c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":164},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"3d28853e76e44abb9a3128d2ee37a792",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":185},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"805a516fc81443b2b650e06f8cef6c93",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":205},
            "size":{
              "width":60,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/游戏画面_1/regen/u10_start.png",
            "end~":"images/游戏画面_1/regen/u10_end.png",
            "line~":"images/游戏画面_1/regen/u10_line.png"}},
{
          "id":"37e2dd65c2f6463c94c3f13056ec7d9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":136},
            "size":{
              "width":9,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de729cc239984162a32730909a3b8fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":136},
                "size":{
                  "width":9,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u34.png"}},
{
          "id":"1fd16e2ff22b499ca7c685f8d896792a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":155},
            "size":{
              "width":9,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52e8852aaec408ea2dfb7f74d827f0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":155},
                "size":{
                  "width":9,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u34.png"}},
{
          "id":"b990e1ff3d514a6f91013f67b5964120",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":176},
            "size":{
              "width":9,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a4729074886439eb4d6323c3e32a09a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":176},
                "size":{
                  "width":9,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u34.png"}},
{
          "id":"1ea60cbe548c4975abf8aa35b08bae68",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":411,
              "y":197},
            "size":{
              "width":9,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c9ded8e302e489ea51a111fc8eddc60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":411,
                  "y":197},
                "size":{
                  "width":9,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u34.png"}},
{
          "id":"21f3c40132e84476a711baf727e8be18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":136},
            "size":{
              "width":16,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50449898e78d4014ab45fae0dc629749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":136},
                "size":{
                  "width":16,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"5768d644898d45dcaaa743afc2a28408",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":157},
            "size":{
              "width":16,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"803cea1fbae3458ca9b16711c5476b1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":157},
                "size":{
                  "width":16,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"57160d8893e34c1389fb67f1d5d9a0a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":179},
            "size":{
              "width":16,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af283587b0c44e5cb4d28ef7c7d9085c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":179},
                "size":{
                  "width":16,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"1ca4881286aa4cf7ba13b254d0685b9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":200},
            "size":{
              "width":16,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1ca680f978f4dee8c39b81c77a93394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":201,
                  "y":200},
                "size":{
                  "width":16,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"ca0500f0931e45ffbf03c79cb5146f1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":440,
              "y":166},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6427b049d574830b408b9ca3548ec6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":440,
                  "y":166},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u50.png"}},
{
          "id":"dec4277a0b3c416db854b7e46c9e365d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":228},
            "size":{
              "width":318,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/游戏画面_1/regen/u52_line.png"}},
{
          "id":"0a8ca00dc26c46efb882bf3093adb43d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":320},
            "size":{
              "width":318,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/游戏画面_1/regen/u52_line.png"}},
{
          "id":"17f8e69b73f14a958e45d79fe122c0a0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":152,
              "y":420},
            "size":{
              "width":318,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/游戏画面_1/regen/u52_line.png"}},
{
          "id":"7c95c3a56ded405c8dc51e371be66db9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":510},
            "size":{
              "width":318,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/游戏画面_1/regen/u52_line.png"}},
{
          "id":"81cd06abf2d44460bfdd9c7dabe063ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"60px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x99CCCCCC,
              "opacity":0.600000023841858},
            "location":{
              "x":188,
              "y":248},
            "size":{
              "width":249,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"516594bc69f840b4a67fb6d9a1d3d6d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"60px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x99CCCCCC,
                  "opacity":0.600000023841858},
                "location":{
                  "x":188,
                  "y":248},
                "size":{
                  "width":249,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ebc790aace045f2a3084b0faef519d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":268},
            "size":{
              "width":53,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"235f8f9489e44de5ad8914962956a1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":268},
                "size":{
                  "width":53,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"5661bfae6bf44de68ed332b81f196c44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":548},
            "size":{
              "width":53,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d4109722b41416091ce002e344922d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":548},
                "size":{
                  "width":53,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"d00b1e20073d4aed94b3cfd8b9cd2dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"60px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x99CCCCCC,
              "opacity":0.600000023841858},
            "location":{
              "x":188,
              "y":341},
            "size":{
              "width":249,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628d079439d948bf962cfbc23f9f21a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"60px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x99CCCCCC,
                  "opacity":0.600000023841858},
                "location":{
                  "x":188,
                  "y":341},
                "size":{
                  "width":249,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73f7992a0a364ceca35b856057ce84fe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":360},
            "size":{
              "width":53,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89efaaab8a174d169c581c4fa321b5b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":360},
                "size":{
                  "width":53,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"fda1b07980124552840983ac3a7f40c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"60px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x99CCCCCC,
              "opacity":0.600000023841858},
            "location":{
              "x":187,
              "y":438},
            "size":{
              "width":249,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"461f3b402a804c889fbbdee9ea4bdee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"60px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x99CCCCCC,
                  "opacity":0.600000023841858},
                "location":{
                  "x":187,
                  "y":438},
                "size":{
                  "width":249,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fac86d436f6a4050827b3fb15bca1deb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":158,
              "y":458},
            "size":{
              "width":53,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb8b59b338b40cf9e6aa90ebaae0172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":158,
                  "y":458},
                "size":{
                  "width":53,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u42.png"}},
{
          "id":"1c77337d836242269da6fa4abaf19508",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"60px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0x99CCCCCC,
              "opacity":0.600000023841858},
            "location":{
              "x":277,
              "y":524},
            "size":{
              "width":61,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5033245e42c94fa5aa869e9310235853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"60px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0x99CCCCCC,
                  "opacity":0.600000023841858},
                "location":{
                  "x":277,
                  "y":524},
                "size":{
                  "width":61,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43a0222a5c1f4ba59a4dbae352a933f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":12},
            "size":{
              "width":265,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"502169cd01ba45fd802d5a34552e39cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":12},
                "size":{
                  "width":265,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c35e56e0486741c7b4e807ccdb8f4f06",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":540,
              "y":60},
            "size":{
              "width":892,
              "height":840}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25dc48c71eb4430590d5a46c78f80201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":540,
                  "y":60},
                "size":{
                  "width":892,
                  "height":840}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4bfc7ef4a894e2391c94e100514abe4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":531},
            "size":{
              "width":62,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c33c3783474caa863f9eb33186f62a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":531},
                "size":{
                  "width":62,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u76.png"}},
{
          "id":"9666f0d993ac448aa21a4f00d4bbb8a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":489},
            "size":{
              "width":109,
              "height":71},
            "rotation":"10",
            "textRotation":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49d79fd7c988491e85acb4a9fd763c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":306,
                  "y":489},
                "size":{
                  "width":109,
                  "height":71},
                "rotation":"10",
                "textRotation":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏画面_1/regen/u78.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "451d1646a98e40c98bd0b8a2d7905760":{
      "scriptId":"u0"},
    "673a81cffa3d473098bff8ceadb621d5":{
      "scriptId":"u1"},
    "07e1d5527d924a37a4fe147fabbf9264":{
      "scriptId":"u2"},
    "ec137798726f48a78af7d1e6196ab145":{
      "scriptId":"u3"},
    "f9c1003f2358478eb4fa2414b71e85f4":{
      "scriptId":"u4"},
    "05e2fcd50bed4b76ab306e4e43769fea":{
      "scriptId":"u5"},
    "6038c64abdeb42c58eb655304ca7820b":{
      "scriptId":"u6"},
    "944fbe3aace149fd883ee6fad6f18f3a":{
      "scriptId":"u7"},
    "bbe0ef78c9c24740af24584316cb6829":{
      "scriptId":"u8"},
    "9692f1d3380144829301ee5774e936c2":{
      "scriptId":"u9"},
    "8572705a1cb244afbdbd8728de1e7adc":{
      "scriptId":"u10"},
    "72349d41325a409b9ca365a96dd71ef4":{
      "scriptId":"u11"},
    "b40ae6922f5e4fae9fadcc338f47e6f5":{
      "scriptId":"u12"},
    "4f449b3d29f54e93bbe20a27b0a34fb1":{
      "scriptId":"u13"},
    "5a5dde7c53d5419193fefa944165f34c":{
      "scriptId":"u14"},
    "478159907dc64297b25dd30549b463c8":{
      "scriptId":"u15"},
    "37f16c4e512940ce9f9a684cb93169fe":{
      "scriptId":"u16"},
    "4a21d37340cf4c329a396a50f7bd1579":{
      "scriptId":"u17"},
    "29dd4441eb3743908f5d99e69b2a9097":{
      "scriptId":"u18"},
    "3c87c564099c42ceb061547874755bdd":{
      "scriptId":"u19"},
    "9fb5d8481f204939907c5b49b13311de":{
      "scriptId":"u20"},
    "09b9d00d754149ac94937213cd1bdd51":{
      "scriptId":"u21"},
    "8c71e41cb7fb40bf887ba200b29b37f1":{
      "scriptId":"u22"},
    "ec8408f447514644bc1f5016c6a5edd3":{
      "scriptId":"u23"},
    "23ca070254b441a8b76cc288a6379576":{
      "scriptId":"u24"},
    "5b75b3ace37f410495cf829ea081ba5e":{
      "scriptId":"u25"},
    "1e4bd85d50744d799cdf00f53ef05626":{
      "scriptId":"u26"},
    "f9ce1c13c7534062bd57e31bed644433":{
      "scriptId":"u27"},
    "163beab19e8e4810a0f88d184841c92e":{
      "scriptId":"u28"},
    "55926679b10e4a6bb9f058a3dd16e5a7":{
      "scriptId":"u29"},
    "dc1269b2da894c25a7fb46585e3381bc":{
      "scriptId":"u30"},
    "766f45261df94d5096ce5d29f2bc007c":{
      "scriptId":"u31"},
    "3d28853e76e44abb9a3128d2ee37a792":{
      "scriptId":"u32"},
    "805a516fc81443b2b650e06f8cef6c93":{
      "scriptId":"u33"},
    "37e2dd65c2f6463c94c3f13056ec7d9c":{
      "scriptId":"u34"},
    "de729cc239984162a32730909a3b8fce":{
      "scriptId":"u35"},
    "1fd16e2ff22b499ca7c685f8d896792a":{
      "scriptId":"u36"},
    "f52e8852aaec408ea2dfb7f74d827f0b":{
      "scriptId":"u37"},
    "b990e1ff3d514a6f91013f67b5964120":{
      "scriptId":"u38"},
    "1a4729074886439eb4d6323c3e32a09a":{
      "scriptId":"u39"},
    "1ea60cbe548c4975abf8aa35b08bae68":{
      "scriptId":"u40"},
    "8c9ded8e302e489ea51a111fc8eddc60":{
      "scriptId":"u41"},
    "21f3c40132e84476a711baf727e8be18":{
      "scriptId":"u42"},
    "50449898e78d4014ab45fae0dc629749":{
      "scriptId":"u43"},
    "5768d644898d45dcaaa743afc2a28408":{
      "scriptId":"u44"},
    "803cea1fbae3458ca9b16711c5476b1e":{
      "scriptId":"u45"},
    "57160d8893e34c1389fb67f1d5d9a0a0":{
      "scriptId":"u46"},
    "af283587b0c44e5cb4d28ef7c7d9085c":{
      "scriptId":"u47"},
    "1ca4881286aa4cf7ba13b254d0685b9c":{
      "scriptId":"u48"},
    "d1ca680f978f4dee8c39b81c77a93394":{
      "scriptId":"u49"},
    "ca0500f0931e45ffbf03c79cb5146f1b":{
      "scriptId":"u50"},
    "c6427b049d574830b408b9ca3548ec6a":{
      "scriptId":"u51"},
    "dec4277a0b3c416db854b7e46c9e365d":{
      "scriptId":"u52"},
    "0a8ca00dc26c46efb882bf3093adb43d":{
      "scriptId":"u53"},
    "17f8e69b73f14a958e45d79fe122c0a0":{
      "scriptId":"u54"},
    "7c95c3a56ded405c8dc51e371be66db9":{
      "scriptId":"u55"},
    "81cd06abf2d44460bfdd9c7dabe063ad":{
      "scriptId":"u56"},
    "516594bc69f840b4a67fb6d9a1d3d6d7":{
      "scriptId":"u57"},
    "3ebc790aace045f2a3084b0faef519d4":{
      "scriptId":"u58"},
    "235f8f9489e44de5ad8914962956a1dc":{
      "scriptId":"u59"},
    "5661bfae6bf44de68ed332b81f196c44":{
      "scriptId":"u60"},
    "4d4109722b41416091ce002e344922d3":{
      "scriptId":"u61"},
    "d00b1e20073d4aed94b3cfd8b9cd2dc8":{
      "scriptId":"u62"},
    "628d079439d948bf962cfbc23f9f21a3":{
      "scriptId":"u63"},
    "73f7992a0a364ceca35b856057ce84fe":{
      "scriptId":"u64"},
    "89efaaab8a174d169c581c4fa321b5b5":{
      "scriptId":"u65"},
    "fda1b07980124552840983ac3a7f40c0":{
      "scriptId":"u66"},
    "461f3b402a804c889fbbdee9ea4bdee4":{
      "scriptId":"u67"},
    "fac86d436f6a4050827b3fb15bca1deb":{
      "scriptId":"u68"},
    "bbb8b59b338b40cf9e6aa90ebaae0172":{
      "scriptId":"u69"},
    "1c77337d836242269da6fa4abaf19508":{
      "scriptId":"u70"},
    "5033245e42c94fa5aa869e9310235853":{
      "scriptId":"u71"},
    "43a0222a5c1f4ba59a4dbae352a933f0":{
      "scriptId":"u72"},
    "502169cd01ba45fd802d5a34552e39cf":{
      "scriptId":"u73"},
    "c35e56e0486741c7b4e807ccdb8f4f06":{
      "scriptId":"u74"},
    "25dc48c71eb4430590d5a46c78f80201":{
      "scriptId":"u75"},
    "c4bfc7ef4a894e2391c94e100514abe4":{
      "scriptId":"u76"},
    "44c33c3783474caa863f9eb33186f62a":{
      "scriptId":"u77"},
    "9666f0d993ac448aa21a4f00d4bbb8a1":{
      "scriptId":"u78"},
    "49d79fd7c988491e85acb4a9fd763c93":{
      "scriptId":"u79"}}});